name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
        include:
          - php: "7.4"
            laravel: "8.*"
            testbench: "^6.0"
          - php: "8.0"
            laravel: "9.*"
            testbench: "^7.0"
          - php: "8.1"
            laravel: "10.*"
            testbench: "^8.0"
          - php: "8.2"
            laravel: "11.*"
            testbench: "^9.0"

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Remove Composer Lock File
        run: |
          if [ -f composer.lock ]; then
            rm composer.lock
          fi

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --dev --no-interaction -W
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction -W
          composer update --prefer-dist --no-interaction -W

      - name: Execute PHPUnit tests
        run: vendor/bin/phpunit
